#ifndef KINFITTER_DICT_H
#define KINFITTER_DICT_H

  #include "KinFitter/TAbsFitConstraint.h"
  #include "KinFitter/TFitConstraintEp.h"
  #include "KinFitter/TFitConstraintEpGaus.h"
  #include "KinFitter/TFitConstraintPt.h"
  #include "KinFitter/TFitConstraintM.h"
  #include "KinFitter/TFitConstraintMGaus.h"
  #include "KinFitter/TFitConstraintMBW.h"
  #include "KinFitter/TAbsFitParticle.h"
  #include "KinFitter/TFitParticlePInvThetaPhi.h"
  #include "KinFitter/TFitParticlePInvThetaPhiE.h"
  #include "KinFitter/TFitParticlePInvThetaPhiM.h"
  #include "KinFitter/TFitParticlePtEtaPhi.h"
  #include "KinFitter/TFitParticlePtEtaPhiE.h"
  #include "KinFitter/TFitParticlePtEtaPhiM.h"
  #include "KinFitter/TFitParticlePThetaPhi.h"
  #include "KinFitter/TFitParticlePThetaPhiE.h"
  #include "KinFitter/TFitParticlePThetaPhiM.h"
  #include "KinFitter/TFitParticlePxPyPz.h"
  #include "KinFitter/TFitParticlePxPyPzE.h"
  #include "KinFitter/TFitParticlePxPyPzM.h"
  #include "KinFitter/TFitParticleRelPtEtaPhi.h"
  #include "KinFitter/TFitParticleRelPtEtaPhiE.h"
  #include "KinFitter/TFitParticleRelPtEtaPhiM.h"
  #include "KinFitter/TFitParticleRelPxPyPz.h"
  #include "KinFitter/TFitParticleRelPxPyPzE.h"
  #include "KinFitter/TFitParticleRelPxPyPzM.h"
  #include "KinFitter/TFitParticleRelE.h"
  #include "KinFitter/TKinFitter.h"
  #include "KinFitter/TGetErrorMatrix.h"
  #include "KinFitter/TToyGentT.h"

#endif
